//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Data.Entity;

    public partial class DebtorsMaster :DbContext
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DebtorsMaster()
        {
            this.Debtors_Transaction = new HashSet<Debtors_Transaction>();
            this.InvoiceHeaders = new HashSet<InvoiceHeader>();
        }
    [Required]
        public string AccountCode { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<decimal> SaleYearToDate { get; set; }
        public Nullable<decimal> CostYearToDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Debtors_Transaction> Debtors_Transaction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceHeader> InvoiceHeaders { get; set; }
    }
}
