//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceDetail
    {
        public int InvoiceNo { get; set; }
        public Nullable<int> ItemNo { get; set; }
        public string StockCode { get; set; }
        public Nullable<int> QtySold { get; set; }
        public Nullable<decimal> UnitCost { get; set; }
        public Nullable<decimal> UnitSell { get; set; }
        public Nullable<int> Disc { get; set; }
        public Nullable<decimal> Total { get; set; }
        public int InvoiceDetailsId { get; set; }
    
        public virtual StockMaster StockMaster { get; set; }
    }
}
