//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock_Transaction
    {
        public int Stock_Transaction_Id { get; set; }
        public string StockCode { get; set; }
        public Nullable<System.DateTime> StockDate { get; set; }
        public string TransactionType { get; set; }
        public Nullable<int> DocumentNo { get; set; }
        public Nullable<int> Qty { get; set; }
        public decimal UnitCost { get; set; }
        public decimal UnitSell { get; set; }
    
        public virtual StockMaster StockMaster { get; set; }
    }
}
